DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
    UserId UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255),
    Email VARCHAR(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    RefreshToken VARCHAR(255) NOT NULL UNIQUE,
    Role VARCHAR(10) NOT NULL CHECK (Role IN ('USER', 'ADMIN')),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ModifiedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CreatedBy VARCHAR(255) DEFAULT NULL,
    ModifiedBy VARCHAR(255) DEFAULT NULL
);
